name: C++ CI

on: [push]

jobs:
  build_linux:

    runs-on: ubuntu-20.04
    
    steps:
    - name: Clone source
      run: git clone --recursive https://github.com/uNetworking/uWebSockets.git
    - name: Build source
      run: make -C uWebSockets
    - name: List binaries
      run: ls uWebSockets
    - name: Install Deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - name: Run smoke test
      run: make -C uWebSockets/tests smoke
    - name: Run unit tests
      run: make -C uWebSockets/tests
      
  build_osx:

    runs-on: macos-latest
    
    steps:
    - name: Clone source
      run: git clone --recursive https://github.com/uNetworking/uWebSockets.git
    - name: Build source
      run: make -C uWebSockets
    - name: List binaries
      run: ls uWebSockets
    - name: Install Deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - name: Run smoke test
      run: make -C uWebSockets/tests smoke
    - name: Run unit tests
      run: make -C uWebSockets/tests
